### PR TITLE
Mycephrebased

### PR DESCRIPTION
**Pull request by msimonin**
Rebased the initial work done on ceph integration
- rework the @asimonet commit to remove what wasn't related to ceph (influx stuffs)
- rebased on top of master

add a commit to refactor and improve the ceph integration by adding options in the reservation.yml

### CODE REVIEW

**Comment by msimonin** [comment]
The bad news is that the first pull is pulled from the docker registry. Even if the private registry seems to have all the images : 

```
curl parapluie-15:4000/v2/_catalog
{"repositories":["kolla/centos-binary-cron","kolla/centos-binary-glance-api","kolla/centos-binary-glance-registry","kolla/centos-binary-haproxy","kolla/centos-binary-heka","kolla/centos-binary-horizon","kolla/centos-binary-keepalived","kolla/centos-binary-keystone","kolla/centos-binary-kolla-toolbox","kolla/centos-binary-mariadb","kolla/centos-binary-memcached","kolla/centos-binary-neutron-dhcp-agent","kolla/centos-binary-neutron-metadata-agent","kolla/centos-binary-neutron-openvswitch-agent","kolla/centos-binary-neutron-server","kolla/centos-binary-nova-api","kolla/centos-binary-nova-conductor","kolla/centos-binary-nova-consoleauth","kolla/centos-binary-nova-libvirt","kolla/centos-binary-nova-novncproxy","kolla/centos-binary-nova-scheduler","kolla/centos-binary-nova-ssh","kolla/centos-binary-openvswitch-db-server","kolla/centos-binary-openvswitch-vswitchd","kolla/centos-binary-rabbitmq"]}
```

We are maybe missing something...

**Comment by asimonet** [comment]
Maybe the images have been updated in the meantime?

**Comment by msimonin** [comment]
It's now working as expected. 
Following : https://github.com/docker/distribution/issues/1853

image

**Comment by msimonin** [comment]
Rebased and update readme :
- add a registry backend section
- add a contributors section

**Comment by msimonin** [comment]
I've made some tests 
The initial run with a fresh rbd will fill the cache, subsequent run will take benefit of the cache : 

### Kolla execution times:

1 controller/storage/network + n computes
- Without cache 

```
n=1 -> 21 min
n=10 -> 30 min 
```
- With cache 

```
n=1 -> 13 min
n=10 -> 18 min 
```

Once merged this could fix https://github.com/BeyondTheClouds/Wiki/issues/20

**Comment by asimonet** [comment]
Just a couple questions:
- why use your own Ceph instead of Didier's?
- can you also commit your changes to reservation.yml?

**Comment by msimonin** [comment]
- Even if reservation.yml is just a sample, I agree we should put didier's parameter by default.
  But maybe, we should pay attention to simultaneous deployments using the same rbd.
- I think reservation.yml has been commited with the ceph section.

**Comment by alebre** [comment]
Regarding the rbd question, See we are doing only read accesses during the deployment, I do not see why we can have issues. IMHO, we should simply guarantee that there is only one writer (i.e. when we populate the rbd)

**Comment by rcherrueau** [comment]
Fixes BeyondTheClouds/Wiki#20

**Pull request merged**
