### PR TITLE
review the reservation process

### PR DESCRIPTION
**Pull request by discovery-git**
With @rcherrueau we reviewed the submission process. 

The outcome is a "simplification" of the reservation mecanism that 
1) get rid of the funk dependency
2) propose a new format for the reservation.yaml

### CODE REVIEW

**Comment by rcherrueau** [comment]
-- Off topic

@msimonin: If I wanna push some modifications into this PR, how I should go?

**Comment by msimonin** [comment]
You can push to the discovery repo. We'll reattribute you the ownerships of the commits afterwards and rebase once we'll agree on the code.
This isn't an ideal situation. I think the next time we peer-code we'll use one our our remote and change the commiter information (see below) to include the other peer programmer.

To include our names in the commit I've exported this variable before commiting :

```
export GIT_AUTHOR_NAME=
export GIT_AUTHOR_EMAIL=
export GIT_COMMITTER_NAME=
export GIT_COMMITTER_EMAIL=
```

**Comment by msimonin** [comment]
Some ideas to continue further with our work and open the discussion : 
-  move the option `force-deploy` definition to the engine (after that I don't see a reason why `KollaG5k` should herit from `G5KEngine`)
-  Another idea is to not generate a fixed `result_dir` directory. Execo provides a way to do so.
-  Subnets are loaded in `get_subnets` that fill `self.subnets` by side effect and use `self.oarjobs` that is set in `load`. Moreover `get_subnets`is only call by `get_free_ip`. _This code smells_.
  I would prefer to load everything about the jobs in one place ; that includes nodes, subnets, vlan.
  (one optimization here could be to cache all the job/roles informations)
- Get rid of `sys.exit` everywhere, throw an exception instead.
-  Change/Clean the method `build_roles`. Ideally I would love to distribute the nodes according a Round Robin policy (see https://github.com/BeyondTheClouds/kolla-g5k/pull/9).

**Comment by rcherrueau** [comment]
Tested under G5K. Everything works like a charm!

**Pull request merged**
